project_id = "paugtcnvqdbjcrrmjxma"

[auth.web3.solana]
enabled = true

[functions.score-updater]
verify_jwt = false

[functions.get-candy-guard]
verify_jwt = false

[functions.get-collection-stats]
verify_jwt = false

[functions.mint-nft-v2]
verify_jwt = false